name: ys_task_your_name
description: YemenSoft Chef Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Networking
  dio: ^5.3.0
  retrofit: ^4.0.1
  logger: ^1.1.0
  
  # Local Storage
  drift: ^2.13.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # JSON Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  flutter_svg: ^2.2.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  retrofit_generator: ^9.7.0
  json_serializable: ^6.7.1
  drift_dev: ^2.13.0
  freezed: ^2.4.2

flutter:
  uses-material-design: true
  generate: true